CREATE SEQUENCE agenda_id_seq AS BIGINT START WITH 1 INCREMENT BY 1;

CREATE TABLE agenda (
  id BIGINT GENERATED BY DEFAULT AS SEQUENCE agenda_id_seq PRIMARY KEY,
  data_agendamento TIMESTAMP,
  observacao VARCHAR(255),
  paciente_id BIGINT,
  psicologo_id BIGINT,
  FOREIGN KEY (psicologo_id) REFERENCES profissional (id),
  FOREIGN KEY (paciente_id) REFERENCES pessoa (id)
);