pipeline {
    agent {
        docker {
            image 'maven:3-alpine' 
            args '-v /root/.m2:/root/.m2' 
        }
    }
    stages {
        stage('Build') { 
            steps {
                sh 'mvn -B -DskipTests clean package' 
                echo 'Building..'
            }
        }
        stage('Unit Tests') {
            steps {
                /**sh 'pwd'
                sh 'mvn test'*/
                echo 'Testing..'
            }
        }
        stage('Deploy') {
            steps {
                /**sh 'java -jar /var/jenkins_home/workspace/service-omega/target/omega-0.0.1-SNAPSHOT.jar &'*/
                echo 'Deploying....'
            }
        }
        stage('Deliver Application') {
            steps {
                sh 'bash ./jenkins/scripts/deliver.sh'
            }
        }
    }
}